# Generated by Django 5.2.14 on 2026-07-03 21:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('przelewy24', 'Przelewy24')], default='przelewy24', max_length=30)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('paid', 'Opłacona'), ('failed', 'Nieudana'), ('cancelled', 'Anulowana')], default='pending', max_length=20)),
                ('method', models.CharField(blank=True, max_length=60)),
                ('p24_token', models.CharField(blank=True, max_length=120)),
                ('p24_order_id', models.CharField(blank=True, max_length=40)),
                ('raw_register', models.JSONField(blank=True, default=dict)),
                ('raw_notification', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payment_status_created_idx')],
            },
        ),
    ]
