# Generated by Django 5.2.14 on 2026-06-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_aesthetic_card_gradient_aesthetic_image_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_is_active', models.BooleanField(default=True)),
                ('announcement_text', models.CharField(blank=True, default='🦇 Darmowa dostawa od 50 zł · 30 dni na zwrot', max_length=255)),
                ('low_stock_default_enabled', models.BooleanField(default=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=3)),
                ('drop_is_active', models.BooleanField(default=True)),
                ('drop_eyebrow', models.CharField(blank=True, default='Najnowszy drop', max_length=120)),
                ('drop_heading', models.CharField(blank=True, default='Najnowszy drop', max_length=180)),
                ('drop_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drop_products', models.ManyToManyField(blank=True, related_name='drop_settings', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Ustawienia strony',
                'verbose_name_plural': 'Ustawienia strony',
            },
        ),
    ]
