# Generated by Django 5.2.14 on 2026-06-23 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body_html', models.TextField(blank=True, help_text='Treść HTML wiadomości.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Przychodząca'), ('outbound', 'Wychodząca')], default='outbound', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('sent', 'Wysłana'), ('received', 'Odebrana')], default='draft', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body_html', models.TextField(blank=True)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.messagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['direction', 'created_at'], name='message_dir_created_idx')],
            },
        ),
    ]
