# Generated by Django 5.2.14 on 2026-06-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_messagetemplate_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'ordering': ['-is_system', 'name']},
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='description',
            field=models.CharField(blank=True, help_text='Kiedy ten mail jest wysyłany.', max_length=255),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='system_key',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
