# Generated by Django 4.2 on 2026-06-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_update_shipping_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
