# Generated by Django 5.2.14 on 2026-07-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_reply_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payments_sandbox',
            field=models.BooleanField(default=True),
        ),
    ]
