# Generated by Django 4.2 on 2026-07-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_upgrade_email_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='drop_eyebrow',
            field=models.CharField(blank=True, default='Nowości', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='drop_heading',
            field=models.CharField(blank=True, default='Nowości', max_length=180),
        ),
    ]
