# Generated by Django 4.2 on 2026-05-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssession',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
