# Generated by Django 5.2.14 on 2026-06-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
