# Generated by Django 4.2 on 2026-07-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_verify_existing_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='order_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
