# Generated by Django 5.2.14 on 2026-05-25 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('catalog', '0003_remove_productvariant_unique_variant_options_per_product_and_more'),
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='outfits',
            field=models.ManyToManyField(blank=True, related_name='articles', to='outfits.outfit'),
        ),
        migrations.AddField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='articles', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.blogcategory'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='article_status_published_idx'),
        ),
    ]
