# Generated by Django 5.2.14 on 2026-05-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('current_step', models.CharField(choices=[('cart', 'Cart'), ('customer', 'Customer'), ('shipping', 'Shipping'), ('review', 'Review')], default='cart', max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
