# Generated by Django 5.2.14 on 2026-07-01 22:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_aesthetic_featured_image'),
        ('orders', '0004_configure_default_shipping_methods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Przyjęcie'), ('out', 'Wydanie')], default='in', max_length=10)),
                ('source', models.CharField(choices=[('opening', 'Stan początkowy'), ('purchase', 'Zakup'), ('complaint', 'Reklamacja'), ('sale', 'Sprzedaż'), ('adjustment', 'Korekta')], default='purchase', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('occurred_at', models.DateField(default=django.utils.timezone.localdate)),
                ('unit_price_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Stawka VAT w procentach, np. 23.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('customs_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Kwota cła (opcjonalnie).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice', models.FileField(blank=True, upload_to='invoices/%Y/%m/')),
                ('supplier_url', models.URLField(blank=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='orders.orderitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['variant', 'occurred_at'], name='stock_variant_date_idx')],
            },
        ),
    ]
