"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env", override=True)


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-dev-spooky-strawberry-local-only",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS")

# Domeny/adresy, którym ufamy przy sprawdzaniu CSRF (wymagane za HTTPS/nginx),
# np. CSRF_TRUSTED_ORIGINS=https://spookystrawberry.pl,https://www.spookystrawberry.pl
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

# nginx przekazuje informację o HTTPS w tym nagłówku — dzięki temu Django
# wie, że żądanie jest bezpieczne (poprawne przekierowania, cookies).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Project apps
    "core",
    "catalog",
    "outfits",
    "cart",
    "analytics",
    "orders",
    "inventory",
    "checkout",
    "payments",
    "blog",
    "accounts",
    "dashboard",
    "ai_tools",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "analytics.middleware.AnalyticsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "cart.context_processors.cart",
                "core.context_processors.site_settings",
                "dashboard.context_processors.unread_messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Authentication / customer accounts
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "accounts:account"
LOGOUT_REDIRECT_URL = "core:home"

# Sesja przeżywa zamknięcie przeglądarki — logowanie i koszyk zostają między sesjami.
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 dni
SESSION_SAVE_EVERY_REQUEST = True  # odświeża ważność przy aktywności

# E-mail — skrzynka pocztowa (cyber-folks.pl).
# Lokalnie, bez konfiguracji w .env, maile trafiają na konsolę. Po ustawieniu
# EMAIL_HOST + EMAIL_HOST_USER (np. w .env) automatycznie wysyłamy realnie przez SMTP.
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "465"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
# Port 465 = SSL (domyślnie u cyber-folks), port 587 = STARTTLS.
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", EMAIL_PORT == 465)
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", False)
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "20"))

# Prefiks doklejany do tematu KAŻDEGO maila.
# Lokalnie DEBUG=True oznacza maile jako testowe; produkcja DEBUG=False zostaje bez prefiksu.
_default_mail_subject_prefix = "[SERWER TESTOWY]" if DEBUG else ""
MAIL_SUBJECT_PREFIX = os.environ.get("MAIL_SUBJECT_PREFIX", _default_mail_subject_prefix)

_default_email_backend = (
    "core.mail_backends.PrefixedSMTPEmailBackend"
    if EMAIL_HOST and EMAIL_HOST_USER
    else "core.mail_backends.PrefixedConsoleEmailBackend"
)
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", _default_email_backend)
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER or "Spooky Strawberry <kontakt@spookystrawberry.pl>",
)
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", EMAIL_HOST_USER or DEFAULT_FROM_EMAIL)

# IMAP - synchronizacja wiadomości przychodzących do panelowej skrzynki.
MAILBOX_IMAP_HOST = os.environ.get("MAILBOX_IMAP_HOST", EMAIL_HOST)
MAILBOX_IMAP_PORT = int(os.environ.get("MAILBOX_IMAP_PORT", "993"))
MAILBOX_IMAP_USE_SSL = env_bool("MAILBOX_IMAP_USE_SSL", True)
MAILBOX_IMAP_USER = os.environ.get("MAILBOX_IMAP_USER", EMAIL_HOST_USER)
MAILBOX_IMAP_PASSWORD = os.environ.get("MAILBOX_IMAP_PASSWORD", EMAIL_HOST_PASSWORD)
MAILBOX_IMAP_FOLDER = os.environ.get("MAILBOX_IMAP_FOLDER", "INBOX")
MAILBOX_SYNC_LIMIT = int(os.environ.get("MAILBOX_SYNC_LIMIT", "50"))


# Płatności — Przelewy24. Trzymamy DWA komplety kluczy: produkcyjny i sandbox.
# To, który jest używany, decyduje przełącznik w panelu (SiteSettings.payments_sandbox),
# a nie zmienna środowiskowa — patrz payments/przelewy24.py.
# Produkcja (z panelu secure.przelewy24.pl):
P24_MERCHANT_ID = os.environ.get("P24_MERCHANT_ID", "")
P24_POS_ID = os.environ.get("P24_POS_ID", "") or P24_MERCHANT_ID
P24_CRC = os.environ.get("P24_CRC", "")
P24_API_KEY = os.environ.get("P24_API_KEY", "")
# Sandbox (z panelu sandbox.przelewy24.pl) — do testów:
P24_SANDBOX_MERCHANT_ID = os.environ.get("P24_SANDBOX_MERCHANT_ID", "")
P24_SANDBOX_POS_ID = os.environ.get("P24_SANDBOX_POS_ID", "") or P24_SANDBOX_MERCHANT_ID
P24_SANDBOX_CRC = os.environ.get("P24_SANDBOX_CRC", "")
P24_SANDBOX_API_KEY = os.environ.get("P24_SANDBOX_API_KEY", "")


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.environ.get("DB_CONN_MAX_AGE", "600")),
            conn_health_checks=True,
            ssl_require=env_bool("DB_SSL_REQUIRE", False),
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pl"

TIME_ZONE = "Europe/Warsaw"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Cel `collectstatic` na produkcji — nginx serwuje ten katalog pod /static/.
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
