# Generated by Django 5.2.14 on 2026-05-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalog_foundations'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_variant_options_per_product',
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', False), ('size__isnull', False)), fields=('product', 'color', 'size'), name='uniq_variant_color_size'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', False), ('size__isnull', True)), fields=('product', 'color'), name='uniq_variant_color_only'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', True), ('size__isnull', False)), fields=('product', 'size'), name='uniq_variant_size_only'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', True), ('size__isnull', True)), fields=('product',), name='uniq_variant_default'),
        ),
    ]
