# Generated by Django 4.2 on 2026-05-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_productvariant_unique_variant_options_per_product_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='cat_product_new_drop_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new_drop',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Szkic'), ('active', 'Aktywny'), ('archived', 'Archiwalny')], default='draft', max_length=20),
        ),
    ]
