# Generated by Django 5.2.14 on 2026-06-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_product_description_and_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='aesthetic',
            name='card_gradient',
            field=models.CharField(blank=True, help_text='Opcjonalny gradient tła kafelka, np. „#2a1622,#7a3d5a”.', max_length=80),
        ),
        migrations.AddField(
            model_name='aesthetic',
            name='image',
            field=models.ImageField(blank=True, upload_to='aesthetics/'),
        ),
        migrations.AddField(
            model_name='aesthetic',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Większy kafelek w mozaice estetyk.'),
        ),
        migrations.AddField(
            model_name='aesthetic',
            name='tagline',
            field=models.CharField(blank=True, help_text='Krótki podtytuł na kafelku estetyki, np. „Mrok, ale delikatny”.', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='disable_low_stock_badge',
            field=models.BooleanField(default=False, help_text='Zaznacz, aby NIE pokazywać oznaczenia „ostatnie sztuki” dla tego produktu.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
