# Generated by Django 5.2.14 on 2026-06-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_aesthetic_card_gradient_aesthetic_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=3, help_text='Etykieta „ostatnie sztuki” pojawia się, gdy łączny stan spadnie do tej liczby lub niżej.'),
        ),
    ]
