# Generated by Django 5.2.14 on 2026-06-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='aesthetic',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Zdjęcie używane tylko, gdy kafelek jest wyróżniony (duży) w mozaice.', upload_to='aesthetics/'),
        ),
    ]
