# Generated by Django 5.2.14 on 2026-07-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Szkic'), ('awaiting_payment', 'Oczekuje na płatność'), ('placed', 'Złożone'), ('confirmed', 'Potwierdzone'), ('packed', 'Spakowane'), ('shipped', 'Wysłane'), ('cancelled', 'Anulowane')], default='draft', max_length=20),
        ),
    ]
