# Generated by Django 5.2.14 on 2026-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
