# Generated by Django 5.2.14 on 2026-07-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_point_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='is_pickup_point',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address_line_1',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
