# Generated by Django 5.2.14 on 2026-07-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_mark_paczkomat_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
    ]
