# Generated by Django 4.2 on 2026-07-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_tracking_number_order_tracking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='once_per_user',
            field=models.BooleanField(default=False),
        ),
    ]
