# Generated by Django 5.2.14 on 2026-05-25 18:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_remove_productvariant_unique_variant_options_per_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('mood_description', models.TextField(blank=True)),
                ('styling_tips', models.TextField(blank=True)),
                ('bundle_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aesthetics', models.ManyToManyField(blank=True, related_name='outfits', to='catalog.aesthetic')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outfits.outfit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outfit_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outfit_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='outfit',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='outfits', through='outfits.OutfitItem', to='catalog.product'),
        ),
        migrations.CreateModel(
            name='OutfitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='outfits/')),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='outfits.outfit')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('outfit',), name='unique_main_image_per_outfit')],
            },
        ),
        migrations.AddConstraint(
            model_name='outfititem',
            constraint=models.UniqueConstraint(fields=('outfit', 'product', 'variant'), name='unique_outfit_product_variant'),
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['status', 'is_featured'], name='outfit_status_featured_idx'),
        ),
    ]
