# Generated by Django 5.2.14 on 2026-05-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_productvariant_unique_variant_options_per_product_and_more'),
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='outfititem',
            name='unique_outfit_product_variant',
        ),
        migrations.AddConstraint(
            model_name='outfititem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('outfit', 'product', 'variant'), name='unique_outfit_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='outfititem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('outfit', 'product'), name='unique_outfit_product_default'),
        ),
    ]
