# Generated by Django 5.2.14 on 2026-06-26 22:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_aesthetic_featured_image'),
        ('outfits', '0002_remove_outfititem_unique_outfit_product_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.DecimalField(decimal_places=2, default=50, help_text='Pozycja w poziomie od lewej krawędzi zdjęcia (0–100%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pozycja X (%)')),
                ('pos_y', models.DecimalField(decimal_places=2, default=50, help_text='Pozycja w pionie od górnej krawędzi zdjęcia (0–100%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pozycja Y (%)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='outfits.outfit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_hotspots', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Punkt na zdjęciu (hotspot)',
                'verbose_name_plural': 'Punkty na zdjęciu (hotspots)',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
